version: '3.8'
services:
  backend:
    env_file:
      - .env
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_started
    restart: always
    ports:
      - ${PORT}:${PORT}
    networks:
      - innerNetwork
    volumes:
      - /usr/src/app/node_modules

  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER={PG_USER}
      - POSTGRES_PASSWORD={PG_PASSWORD}
      - POSTGRES_DB={PG_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - innerNetwork
    ports:
      - ${PG_PORT}:${PG_PORT}

volumes:
  postgres:
networks:
  innerNetwork:
    driver: bridge